// WORKOUT STATE
export const ADD_WORKOUT = 'ADD_WORKOUT'
export const UPDATE_WORKOUT = 'UPDATE_WORKOUT'
export const DELETE_WORKOUT = 'DELETE_WORKOUT'
export const LIKE_WORKOUT = 'LIKE_WORKOUT'

// EXERCISE STATE
export const ADD_EXERCISE = 'ADD_EXERCISE'
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE'
export const DELETE_EXERCISE = 'DELETE_EXERCISE'
export const REMOVE_FAVOURITE_EXERCISE = 'REMOVE_FAVOURITE_EXERCISE'

// CATEGORY STATE
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'

// VIDEO STATE
export const PAUSE_VIDEO = 'PAUSE_VIDEO'
export const CHANGE_VIDEO = 'CHANGE_VIDEO'
export const VIDEO_LOADED = 'VIDEO_LOADED'
export const VIDEO_PROGRESS = 'VIDEO_PROGRESS'
export const LOAD_WORKOUT = 'LOAD_WORKOUT'

// USER STATE
export const GET_USER = 'GET_USER'

// UI STATE
export const SWITCH_CATEGORY = 'SWITCH_CATEGORY'
export const EDIT_FAVOURITE_EXERCISES_FLAG = 'EDIT_FAVOURITE_EXERCISES_FLAG'
export const EDIT_FAVOURITE_EXERCISES_DONE = 'EDIT_FAVOURITE_EXERCISES_DONE'
export const SET_NEW_WORKOUT_ID = 'SET_NEW_WORKOUT_ID' 
