// WORKOUT STATE
export const ADD_WORKOUT = 'ADD_WORKOUT'
export const UPDATE_WORKOUT_LOCAL = 'UPDATE_WORKOUT_LOCAL' // due to lack of better name
export const POPULATE_WORKOUT = 'POPULATE_WORKOUT'
export const DELETE_WORKOUT = 'DELETE_WORKOUT'
export const LIKE_WORKOUT = 'LIKE_WORKOUT'

// EXERCISE STATE
export const ADD_EXERCISE = 'ADD_EXERCISE'
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE'
export const DELETE_EXERCISE = 'DELETE_EXERCISE'
export const REMOVE_FAVOURITE_EXERCISE = 'REMOVE_FAVOURITE_EXERCISE'
export const LIKE_EXERCISE = 'LIKE_EXERCISE'
export const UPDATE_EXERCISE_LOCAL = 'UPDATE_EXERCISE_LOCAL'

// CATEGORY STATE
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'

// VIDEO STATE
export const PAUSE_VIDEO = 'PAUSE_VIDEO'
export const CHANGE_VIDEO = 'CHANGE_VIDEO'
export const VIDEO_LOADED = 'VIDEO_LOADED'
export const VIDEO_PROGRESS = 'VIDEO_PROGRESS'
export const LOAD_WORKOUT = 'LOAD_WORKOUT'
export const TOGGLE_PAUSE_MODAL = 'TOGGLE_PAUSE_MODAL'

// USER STATE
export const SET_USER = 'SET_USER'
export const FETCH_USER = 'FETCH_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_LOCAL = 'UPDATE_USER_LOCAL'
export const POPULATE_USERS = 'POPULATE_USERS'

// UI STATE
export const CHANGE_BROWSE_TAB = 'CHANGE_BROWSE_TAB'
export const SWITCH_CATEGORY = 'SWITCH_CATEGORY'
export const EDIT_FAVOURITE_EXERCISES_FLAG = 'EDIT_FAVOURITE_EXERCISES_FLAG'
export const EDIT_FAVOURITE_EXERCISES_DONE = 'EDIT_FAVOURITE_EXERCISES_DONE'
export const MODAL_DELETE_EXERCISE = 'MODAL_DELETE_EXERCISE'

export const SET_NEW_WORKOUT_ID = 'SET_NEW_WORKOUT_ID'

// Async States ahead
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const FETCH_CATEGORY_DETAILS = 'FETCH_CATEGORY_DETAILS'
export const POST_WORKOUT = 'POST_WORKOUT'
export const UPDATE_WORKOUT = 'UPDATE_WORKOUT'

export const ADD_FEATURED_WORKOUTS = 'ADD_FEATURED_WORKOUTS'
export const FETCH_FEATURED_WORKOUTS = 'FETCH_FEATURED_WORKOUTS'

export const ADD_TRENDING_WORKOUTS = 'ADD_TRENDING_WORKOUTS'
export const FETCH_TRENDING_WORKOUTS = 'FETCH_TRENDING_WORKOUTS'

export const ADD_MOST_POPULAR_WORKOUTS = 'ADD_MOST_POPULAR_WORKOUTS'
export const FETCH_MOST_POPULAR_WORKOUTS = 'FETCH_MOST_POPULAR_WORKOUTS'

export const POPULATE_WORKOUT_EXERCISES = 'POPULATE_WORKOUT_EXERCISES'
export const FETCH_WORKOUT_EXERCISES = 'FETCH_WORKOUT_EXERCISES'

export const POPULATE_RECENT_WORKOUTS = 'POPULATE_RECENT_WORKOUTS'
export const FETCH_RECENT_WORKOUTS = 'FETCH_RECENT_WORKOUTS'

export const POPULATE_FAVOURITE_WORKOUTS = 'POPULATE_FAVOURITE_WORKOUTS'
export const POPULATE_FAVOURITE_EXERCISES = 'POPULATE_FAVOURITE_EXERCISES'
export const FETCH_FAVOURITE_WORKOUTS = 'FETCH_FAVOURITE_WORKOUTS'
export const FETCH_FAVOURITE_EXERCISES = 'FETCH_FAVOURITE_EXERCISES'

export const ADD_PURE_EXERCISE = 'ADD_PURE_EXERCISE'
export const POPULATE_PURE_EXERCISE = 'POPULATE_PURE_EXERCISE'

// login action types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const CLEAR_ERROR = 'CLEAR_ERROR'

// search actions types
export const FETCH_SEARCH_RESULT = 'FETCH_SEARCH_RESULT'
export const GET_SEARCH_RESULT = 'GET_SEARCH_RESULT'
